---
- name: Init Docker
  hosts: app
  tasks:
    - name: Install Docker
      become: true
      package:
        name: docker
        state: present
    - name: Start Docker daemon
      become: true
      service:
        name: docker
        state: started
- name: Init Postgres server
  hosts: database
  tasks:
    - name: Intsall Postgres server
      become: true
      apt:
        name: 'postgresql-{{ postgres_version }}'
        state: present
    - name: Change Postgres data dir
      become: true
      lineinfile:
        path: '/etc/postgresql/{{ postgres_version }}/main/postgresql.conf'
        regexp: '^data_directory'
        line: 'data_directory = ''{{ postgres_data_dir }}'''
    - name: Start Postgres server
      become: true
      service:
        name: postgresql
        state: started